name: Prettier Check
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ "main" ]
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --save-dev --save-exact prettier

      - name: Check formatting with Prettier
        run: pnpm prettier:write
